name: Deploy
on:
  push:
    branches:
      - master
  #手动触发
  workflow_dispatch:

permissions:
  contents: write    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 检出代码
        uses: actions/checkout@v4
        with: 
          submodules: 'true'

      - name: 安装node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装Hexo-cli 和 其他 node 环境
        run: |
          npm install hexo-cli -g
          npm install

      - name: 构建静态页面
        run: |
          hexo g

      # - name: 你也可以在这里执行更多Linux命令
      #   run: |
      #     echo Example

      - name: 推送到 deploy 分支 # 部署
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: deploy # 部署后提交到的分支
          folder: public # 打包好的目录名称
